# -*- coding: utf-8 -*-
"""test_lucarne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTaW7TgTKwLeqDdmHMuxkJ1kCQ50VyjD

- Annoter les photos dans LabelImg, en sortir le format Yolo: un dossier avec les images (images/), et un dossier avec les labels(labels/: un fichier txt du nom de la photo avec dedans le class_img x_center y_center width height)
Note: un script csv_to_yolo_txt.py existe pour le faire si l'on n'a qu'un csv
Note2: pas de caractères spéciaux (espace, accent, cédille, etc) dans les noms des photos.
- Utiliser le script make....py pour créer les ficheirs train.txt et val.txt qui comprenent les noms des photos qui ont été annoté: 95% va dans train, 5% dans val)
- Modifier yolov3_csutom_train.cfg dans cfg/ si besoin en fonction du nombre classes
- Dans yolo.names, lister les classes utilisées dans l'annotation: la ligne 1 correspondra à la classe 0 des lignes des fichiers txt, la 2 au 1, etc
- `!zip -r darknet.zip darknet/`, puis mettre ce zip à la racine du drive
"""

from google.colab import drive
drive.mount('/content/drive')

!nvcc --version

!unzip "/content/drive/My Drive/darknet.zip"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet 
!make
!chmod +x ./darknet

!rm /content/darknet/backup -r
!ln -s /content/drive/'My Drive'/backup /content/darknet

!sudo apt install dos2unix

!dos2unix ./data/train.txt
!dos2unix ./data/val.txt
!dos2unix ./data/yolo.data
!dos2unix ./data/yolo.names
!dos2unix ./cfg/yolov3_custom_train.cfg

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet
!./darknet detector train data/yolo.data cfg/yolov3_custom_train.cfg darknet53.conv.74

"""- A la racine du drive, dans le dossier test_images/, mettre toutes les photos dont on veut prédire les mots-clés
- Dans le notebook validation_lucarne.ipynb, changer le chemin vers le fichier de weights qui doit être dans backup/
- Vider le dossier predict/
- Lancer le notebook validation_lucarne.ipynb, la sortie se fait dans predict/
"""